### ISSUE TITLE
Problem with expired certificates

### ISSUE THREAD

**Issue by pmauchle** [admin-ch/CovidCertificate-SDK-iOS#91]
We have successfully implemented the SDK in our app, and checking certificates works, but not in the case of expired certificates. They always show valid. This problem is only in iOS. We don't have a problem with the Android SDK.

Here is how we test:`
```
let result: Result<VerifierCertificateHolder, CovidCertError> = CovidCertificateSDK.Verifier.decode(encodedData: data);

switch result {
case .success(let certHolder):
        CovidCertificateSDK.Verifier.check(holder: certHolder, forceUpdate: false) {result in

        ... here, we check nationalRules, signature and revocationStatus and they are all valid
```
![image](https://user-images.githubusercontent.com/3627771/132661515-b9dadfe9-7860-43d0-a705-4147e401b5ca.png)

The "Covid check" app shows following:
![image](https://user-images.githubusercontent.com/3627771/132661720-83914406-e2e7-4198-8064-357743620158.png)

How do we check if the certificate is expired?

**Comment by pmauchle** [comment]
This problem is solved after updating to the newest version of the swift package

**Comment by pmauchle** [comment]
Unfourtanly the error still occurs after updating to the latest version. Also now I'm getting NETWORK_PARSE_ERROR errors while testing.

**Comment by stmitt** [comment]
@pmauchle we'll look into it. Which version of the SDK are you using?

**Comment by pmauchle** [comment]
@stmitt I just added the SDK again this morning in the swift package manager and use this git repo with the branch main.
![image](https://user-images.githubusercontent.com/3627771/132694231-7d3b7d55-23d9-41cd-a9d8-75401310bc75.png)

**Comment by stmitt** [comment]
@pmauchle can you try specifying the [1.0.1](https://github.com/admin-ch/CovidCertificate-SDK-iOS/releases/tag/v1.0.1)  release. The main branch uses a not yet deployed backend.

**Comment by pmauchle** [comment]
@stmitt I get a dependency error: 
`Dependencies could not be resolved because package 'covidcertificate-sdk-ios' is required using a stable-version but 'covidcertificate-sdk-ios' depends on an unstable-version package 'swiftcbor' and root depends on 'CovidCertificate-SDK-iOS' 1.0.1.
`

**Comment by pmauchle** [comment]
@stmitt I get an error with `SecTrustEvaluateWithError`, probably this commit would fix it. 

https://github.com/admin-ch/CovidCertificate-SDK-iOS/commit/b4e64e48c32174ea39979d002b55a272c68029c8#diff-fa8ca0c7a18dead3a5acad8edb89e43ff05841d344bd77b8f6ef58ecf43587c3

**Comment by stmitt** [comment]
@pmauchle Yes indeed, does it work by setting `.revision("b4e64e48c32174ea39979d002b55a272c68029c8")`?

**Comment by pmauchle** [comment]
@stmitt that worked, I was able to add it in the swift package manager and build it.

But I still get **NETWORK_PARSE_ERROR** in the nationalRules. I used the same API key as in our app which is live and the scanning there works, with the exception of expired certificates.
![image](https://user-images.githubusercontent.com/3627771/132822001-436d510a-3f2d-4eec-b6ad-d4c3cf10514c.png)

**Comment by stmitt** [comment]
Can you check what the backend is returning for this network request? I just tried the SDK with this specific commit and it works fine. Can you check if you use the API key for the correct environment?

**Comment by stmitt** [comment]
@pmauchle  I just noticed in your initial post: while the national rule check was technically successful and no error occurred the `isValid` flag is set to false and therefore the certificate is not valid anymore.
> ![image](https://user-images.githubusercontent.com/3627771/132661515-b9dadfe9-7860-43d0-a705-4147e401b5ca.png)

**Comment by pmauchle** [comment]
@stmitt it works now in dev environment, I used the prod API keys. I did not know that I have to check even further in the nartionalRules, thanks for pointing that out. I will report if the problem is also solved in Testflight & Live.

**Comment by pmauchle** [comment]
@stmitt it works on TestFlight, thank you very much for you help!
